# Generated by Django 5.0.14 on 2025-11-12 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Nizomjon Urolov",
                        help_text="Your full name",
                        max_length=200,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Junior Web Developer | Cybersecurity Enthusiast",
                        help_text="Your professional title",
                        max_length=200,
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        default="Passionate about building clean, responsive, and user-friendly websites. Currently strengthening cybersecurity skills to create secure and efficient web applications.",
                        help_text="Short biography",
                    ),
                ),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True,
                        help_text="Your profile photo",
                        null=True,
                        upload_to="profile/",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        default="nizomjonurolov24@gmail.com", max_length=254
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, default="+998 95-039-36-69", max_length=50
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, default="Pilla street, 78, Tashkent", max_length=200
                    ),
                ),
                (
                    "github_url",
                    models.URLField(
                        blank=True, default="https://github.com/urolovforever"
                    ),
                ),
                (
                    "linkedin_url",
                    models.URLField(
                        blank=True, default="https://www.linkedin.com/in/nizomjonurolov"
                    ),
                ),
                (
                    "telegram_url",
                    models.URLField(blank=True, default="https://t.me/urolovnizomjon"),
                ),
                (
                    "cv_file",
                    models.FileField(
                        blank=True,
                        help_text="Upload your CV/Resume PDF",
                        null=True,
                        upload_to="cv/",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Profile",
                "verbose_name_plural": "Profile",
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(help_text="Project title", max_length=200)),
                (
                    "description",
                    models.TextField(help_text="Detailed project description"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Project screenshot or thumbnail",
                        null=True,
                        upload_to="projects/",
                    ),
                ),
                (
                    "github_link",
                    models.URLField(
                        blank=True, help_text="GitHub repository URL", null=True
                    ),
                ),
                (
                    "live_link",
                    models.URLField(blank=True, help_text="Live demo URL", null=True),
                ),
                (
                    "technologies",
                    models.CharField(
                        blank=True,
                        help_text="Technologies used (comma-separated)",
                        max_length=500,
                    ),
                ),
                (
                    "project_type",
                    models.CharField(
                        blank=True,
                        help_text="Type of project (e.g., Web App, Mobile App, API)",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
                "ordering": ["-created_at"],
            },
        ),
    ]
